language: go # wither art thou, Go?

go:
 - 1.7

install:
 - mkdir -p $HOME/bin || true
 - mkdir -p $HOME/pkg || true
 - mkdir -p $HOME/src/github.com/jgcallero || true
 - export GOPATH=$HOME
 - export PATH=$PATH:$HOME/go/bin
 - go get -v github.com/jgcallero/gokerb

script:
 - cd $HOME/src/github.com/jgcallero/gokerb && go build -v .
 - cd $HOME/src/github.com/jgcallero/gokerb && go test -v .
